data_root_dir: ../../../data2/saif/eating/data/

label_root_dir: labels_folder

random_split: true

num_classes: 2

participants: 
  pilot_study: ['R01', 'R02', 'R02-face', 'R02-face2', 'R03', 'R03-face', 
          'R03-face2', 'R04-face', 'R04-face2', 'R04-face3']
  pilot_frame_off: ['R02_hand_02', 'R02_wild', 'R02_wild_03', 'R04-hand2']
  # user_study: ['P01', 'P01-wild', 'P03', 'P03-wild', 'P04', 'P05', 'P05-wild', 'P06', 'P06-wild', 'P07', 'P07-wild', 
  #       'P08', 'P09', 'P09-wild', 'P10', 'P10-wild', 'P11', 'P11-wild', 'P15-wild', 'P16-wild', 'P17-wild', 'P18-wild',
  #       'R01', 'R02', 'R03' ]

split:
  #pilot_study
  train: ['R01', 'R02', 'R02-face', 'R02-face2', 'R03',  'R04-face3'] #'R02_hand_02', 'R02_wild',
  val: ['R04-face2', 'R03-face'] # 'R02_wild_03',
  test: ['R03-face2', 'R04-face'] # 'R04-hand2'

