mobilenet_v3:
  input_channels: 3
  output_dim: 2
  learning_rate: 1.0e-3
  loss_function: 'focal-loss' #'cross-entropy' # 
  class_weights: [] # default: [] | [10, 11, 19]
  lr_scheduler:  'multistep_lr' #'cosine_annealing'